title: The Cursed Blacksmith
description: Minecraft Bedrock mod creator

remote_theme: carlosperate/jekyll-theme-rtd

site_favicon: 'https://avatars.githubusercontent.com/u/81420586?v=4'
sticky_navigation: true
prev_next_buttons_location: both

# Development server config, needed to load some of the content
webrick:
  headers:
    Access-Control-Allow-Origin: "*"

# Theme settings
site_author: Abcdavk
repo_url: 'https://github.com/abcdavk/abcdavk'
edit_on_github: true
github_docs_folder: false
sticky_navigation: true
prev_next_buttons_location: both
search_enabled: false
hljs_style: github-gist
